# fly.toml app configuration file generated for bloomapp-2 on 2025-04-01T10:17:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloomapp-2'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
